# Generated by Django 5.1.5 on 2026-08-31 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RetailStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ms_id", models.UUIDField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "store_ms_id",
                    models.UUIDField(
                        blank=True, help_text="Bog'langan ombor", null=True
                    ),
                ),
                ("organization_ms_id", models.UUIDField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Savdo nuqtasi",
                "verbose_name_plural": "Savdo nuqtalari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=64, unique=True)),
                ("cursor", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("rows_synced", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sinxronizatsiya holati",
                "verbose_name_plural": "Sinxronizatsiya holati",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ms_id", models.UUIDField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=512)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "discount_card",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "balance",
                    models.BigIntegerField(
                        default=0, help_text="Tiyinlarda; musbat = avans"
                    ),
                ),
                (
                    "sales_amount",
                    models.BigIntegerField(
                        default=0, help_text="Umumiy savdo, tiyinlarda"
                    ),
                ),
                ("bonus_points", models.IntegerField(default=0)),
                (
                    "accumulation_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Nakopitelniy chegirma, %",
                        max_digits=5,
                    ),
                ),
                (
                    "personal_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Shaxsiy chegirma, %",
                        max_digits=5,
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mijoz",
                "verbose_name_plural": "Mijozlar",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["phone"], name="catalog_cus_phone_d04d50_idx"),
                    models.Index(
                        fields=["discount_card"], name="catalog_cus_discoun_3ee68d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ms_id", models.UUIDField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("path_name", models.CharField(blank=True, max_length=512)),
                ("archived", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.productfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tovar guruhi",
                "verbose_name_plural": "Tovar guruhlari",
                "ordering": ["path_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ms_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("product", "Tovar"),
                            ("variant", "Modifikatsiya"),
                            ("service", "Xizmat"),
                            ("bundle", "Komplekt"),
                        ],
                        default="product",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=512)),
                ("code", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "article",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "sale_price",
                    models.BigIntegerField(default=0, help_text="Tiyinlarda"),
                ),
                (
                    "uom_name",
                    models.CharField(
                        blank=True, help_text="dona, kg, litr", max_length=64
                    ),
                ),
                (
                    "is_weight",
                    models.BooleanField(
                        default=False, help_text="Vaznli tovar — tarozida tortiladi"
                    ),
                ),
                (
                    "plu",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Tarozidagi PLU raqami (vaznli tovarlar uchun)",
                        null=True,
                    ),
                ),
                ("vat", models.IntegerField(blank=True, null=True)),
                (
                    "tracked",
                    models.BooleanField(default=False, help_text="Markirovkali tovar"),
                ),
                ("archived", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.productfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tovar",
                "verbose_name_plural": "Tovarlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_ms_id", models.UUIDField(db_index=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qoldiq",
                "verbose_name_plural": "Qoldiqlar",
            },
        ),
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=128)),
                (
                    "kind",
                    models.CharField(
                        blank=True, help_text="ean13, code128, ...", max_length=16
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shtrix-kod",
                "verbose_name_plural": "Shtrix-kodlar",
                "indexes": [
                    models.Index(fields=["value"], name="catalog_bar_value_5606ee_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["archived", "name"], name="catalog_pro_archive_7c601d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("product", "store_ms_id")},
        ),
    ]
