# Generated by Django 5.1.5 on 2026-09-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailstore",
            name="price_type_ms_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="retailstore",
            name="price_type_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
