# Generated by Django 5.1.5 on 2026-09-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_retailstore_price_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ms_id", models.UUIDField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("sort", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Narx turi",
                "verbose_name_plural": "Narx turlari",
                "ordering": ["sort", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="prices",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
