# Generated by Django 5.1.5 on 2026-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_price_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ms_id", models.UUIDField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("path_name", models.CharField(blank=True, max_length=512)),
                ("archived", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ombor",
                "verbose_name_plural": "Omborlar",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="retailstore",
            name="manual_warehouse_ms_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Qo'lda tanlangan ombor"
            ),
        ),
    ]
