# Generated by Django 5.1.5 on 2026-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_warehouses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ms_id", models.UUIDField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Tashkilot",
                "verbose_name_plural": "Tashkilotlar",
                "ordering": ["name"],
            },
        ),
    ]
