# Generated by Django 5.1.5 on 2026-08-31 17:00

import django.db.models.deletion
import sales.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("is_cash", models.BooleanField(default=False)),
                ("ms_account_id", models.UUIDField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("sort", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "To'lov turi",
                "verbose_name_plural": "To'lov turlari",
                "ordering": ["sort", "name"],
            },
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
                (
                    "api_token",
                    models.CharField(
                        db_index=True,
                        default=sales.models.new_api_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registers",
                        to="catalog.retailstore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kassa",
                "verbose_name_plural": "Kassalar",
                "ordering": ["store__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("sale", "Savdo"), ("return", "Qaytarish")],
                        default="sale",
                        max_length=8,
                    ),
                ),
                ("number", models.IntegerField(help_text="Smena ichidagi chek raqami")),
                (
                    "local_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "gross_total",
                    models.BigIntegerField(default=0, help_text="Chegirmasiz"),
                ),
                ("discount_total", models.BigIntegerField(default=0)),
                (
                    "points_spent",
                    models.IntegerField(default=0, help_text="Ball bilan to'langani"),
                ),
                ("points_earned", models.IntegerField(default=0)),
                (
                    "net_total",
                    models.BigIntegerField(default=0, help_text="To'langan summa"),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("new", "Navbatda"),
                            ("sent", "Yuborilgan"),
                            ("failed", "Xato"),
                            ("stuck", "Tiqilib qolgan"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=8,
                    ),
                ),
                ("sync_attempts", models.IntegerField(default=0)),
                ("sync_error", models.TextField(blank=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("ms_demand_id", models.UUIDField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="catalog.customer",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chek",
                "verbose_name_plural": "Cheklar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField(help_text="Tiyinda")),
                (
                    "local_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tendered", models.BigIntegerField(blank=True, null=True)),
                ("change", models.BigIntegerField(blank=True, null=True)),
                ("ms_payment_id", models.UUIDField(blank=True, null=True)),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.paymentmethod",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov",
                "verbose_name_plural": "To'lovlar",
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("ms_product_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(max_length=512)),
                ("barcode", models.CharField(blank=True, max_length=64)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=14),
                ),
                ("price", models.BigIntegerField(help_text="Birlik narxi, tiyinda")),
                (
                    "discount",
                    models.BigIntegerField(
                        default=0, help_text="Qator chegirmasi, tiyinda"
                    ),
                ),
                (
                    "total",
                    models.BigIntegerField(
                        help_text="Chegirmadan keyingi qator summasi"
                    ),
                ),
                ("mark_code", models.CharField(blank=True, max_length=256)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chek qatori",
                "verbose_name_plural": "Chek qatorlari",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(help_text="Kassa bo'yicha tartib raqami"),
                ),
                ("cashier", models.CharField(max_length=128)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Ochiq"), ("closed", "Yopilgan")],
                        default="open",
                        max_length=8,
                    ),
                ),
                (
                    "opening_cash",
                    models.BigIntegerField(default=0, help_text="Razmen, tiyinda"),
                ),
                (
                    "counted_cash",
                    models.BigIntegerField(
                        blank=True, help_text="Kassir sanagani, tiyinda", null=True
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="sales.register",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smena",
                "verbose_name_plural": "Smenalar",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="sales.shift",
            ),
        ),
        migrations.CreateModel(
            name="CashOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("in", "Kiritildi"), ("out", "Chiqarildi")],
                        max_length=4,
                    ),
                ),
                ("amount", models.BigIntegerField(help_text="Musbat son, tiyinda")),
                ("comment", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_ops",
                        to="sales.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kassa operatsiyasi",
                "verbose_name_plural": "Kassa operatsiyalari",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["status", "-opened_at"], name="sales_shift_status_990bb4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("register", "number")},
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["sync_status", "next_attempt_at"],
                name="sales_sale_sync_st_9e8efb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["-created_at"], name="sales_sale_created_66311a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sale",
            unique_together={("shift", "kind", "number")},
        ),
    ]
