# Generated by Django 5.1.5 on 2026-09-01 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cashier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("login", models.SlugField(max_length=64, unique=True)),
                ("pin_hash", models.CharField(max_length=256)),
                (
                    "is_manager",
                    models.BooleanField(default=False, verbose_name="Katta huquqlar"),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Kassir",
                "verbose_name_plural": "Kassirlar",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="shift",
            name="cashier_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="sales.cashier",
            ),
        ),
    ]
