# Generated by Django 5.1.5 on 2026-09-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_cashier_shift_cashier_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="login",
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="register",
            name="password_hash",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
