# Generated by Django 5.1.5 on 2026-09-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_register_login_register_password_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Yoqilgan")),
                (
                    "organization",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Tashkilot"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Hisob raqam",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Manzil"
                    ),
                ),
                (
                    "access_group",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Kirish"
                    ),
                ),
                (
                    "allow_choose_cashier",
                    models.BooleanField(
                        default=False, verbose_name="Sotuvda kassirni tanlashga ruxsat"
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        blank=True,
                        default="Chakana narx",
                        max_length=64,
                        verbose_name="Narx turi",
                    ),
                ),
                (
                    "allow_price_edit",
                    models.BooleanField(
                        default=False,
                        verbose_name="Sotuvda narxni o'zgartirishga ruxsat",
                    ),
                ),
                (
                    "allow_delete_line",
                    models.BooleanField(
                        default=True,
                        verbose_name="Chekdan alohida qatorni o'chirishga ruxsat",
                    ),
                ),
                (
                    "allow_discount",
                    models.BooleanField(
                        default=True,
                        verbose_name="Chek va qatorlarga chegirma berishga ruxsat",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="Eng ko'p chegirma (%)",
                    ),
                ),
                (
                    "warehouse",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Ombor"
                    ),
                ),
                (
                    "allow_create_product",
                    models.BooleanField(
                        default=False, verbose_name="Kassada tovar yaratishga ruxsat"
                    ),
                ),
                (
                    "track_stock",
                    models.BooleanField(
                        default=False, verbose_name="Qoldiqni hisobga olish"
                    ),
                ),
                (
                    "track_reserves",
                    models.BooleanField(
                        default=False, verbose_name="Rezervni hisobga olish"
                    ),
                ),
                (
                    "show_product_groups",
                    models.CharField(
                        choices=[
                            ("all", "Barcha guruhlar"),
                            ("selected", "Tanlangan guruhlar"),
                        ],
                        default="all",
                        max_length=16,
                        verbose_name="Kassada ko'rsatiladigan tovar guruhlari",
                    ),
                ),
                (
                    "add_customers_to_groups",
                    models.BooleanField(
                        default=False, verbose_name="Yangi mijozlarni guruhga qo'shish"
                    ),
                ),
                (
                    "show_customer_groups",
                    models.CharField(
                        choices=[
                            ("all", "Barcha guruhlar"),
                            ("selected", "Tanlangan guruhlar"),
                        ],
                        default="all",
                        max_length=16,
                        verbose_name="Kassada ko'rsatiladigan mijoz guruhlari",
                    ),
                ),
                (
                    "upload_customers_offline",
                    models.BooleanField(
                        default=True, verbose_name="Mijozlarni oflayn ish uchun yuklash"
                    ),
                ),
                (
                    "req_fio",
                    models.BooleanField(default=True, verbose_name="F.I.Sh majburiy"),
                ),
                (
                    "req_phone",
                    models.BooleanField(default=True, verbose_name="Telefon majburiy"),
                ),
                (
                    "req_card",
                    models.BooleanField(
                        default=True, verbose_name="Bonus karta raqami majburiy"
                    ),
                ),
                (
                    "req_email",
                    models.BooleanField(
                        default=False, verbose_name="Elektron pochta majburiy"
                    ),
                ),
                (
                    "req_birthday",
                    models.BooleanField(
                        default=False, verbose_name="Tug'ilgan sana majburiy"
                    ),
                ),
                (
                    "req_gender",
                    models.BooleanField(default=False, verbose_name="Jins majburiy"),
                ),
                (
                    "require_fiscal_receipt",
                    models.BooleanField(
                        default=False,
                        verbose_name="Kassa cheklarini majburiy shakllantirish",
                    ),
                ),
                (
                    "test_print_modes",
                    models.BooleanField(
                        default=False,
                        verbose_name="Kassada chek chop etish rejimlarini sinash",
                    ),
                ),
                (
                    "autoprint_nonfiscal",
                    models.BooleanField(
                        default=True,
                        verbose_name="Nofiskal operatsiyalar uchun tovar chekini avto chop etish",
                    ),
                ),
                (
                    "autoprint_fiscal",
                    models.BooleanField(
                        default=False,
                        verbose_name="Fiskal operatsiyalar uchun tovar chekini avto chop etish",
                    ),
                ),
                (
                    "card_acquirer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Karta — bank-ekvayer",
                    ),
                ),
                (
                    "card_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Ekvayer komissiyasi (%)",
                    ),
                ),
                (
                    "qr_acquirer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="QR — bank-ekvayer",
                    ),
                ),
                (
                    "shift_create_incoming_cashless",
                    models.BooleanField(
                        default=True,
                        verbose_name="Smena yopilganda naqdsiz tushum uchun kirim to'lov",
                    ),
                ),
                (
                    "shift_create_cash_order",
                    models.BooleanField(
                        default=True,
                        verbose_name="Smena yopilganda naqd tushum uchun kirim order",
                    ),
                ),
                (
                    "allow_returns_closed_shift",
                    models.BooleanField(
                        default=False,
                        verbose_name="Yopiq smenalarda qaytarishga ruxsat",
                    ),
                ),
                (
                    "allow_returns_no_reason",
                    models.BooleanField(
                        default=False, verbose_name="Asossiz qaytarishga ruxsat"
                    ),
                ),
                (
                    "orders_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Buyurtma va oldindan to'lov"
                    ),
                ),
                (
                    "allow_advances",
                    models.BooleanField(
                        default=False,
                        verbose_name="Avans qabul qilish va undan to'lash",
                    ),
                ),
                (
                    "allow_certificates",
                    models.BooleanField(
                        default=False,
                        verbose_name="Sovg'a sertifikatlarini sotish va qabul qilish",
                    ),
                ),
                (
                    "credit_sales_enabled",
                    models.BooleanField(default=False, verbose_name="Qarzga sotish"),
                ),
                (
                    "expense_receipts_enabled",
                    models.BooleanField(default=False, verbose_name="Xarajat cheklari"),
                ),
                (
                    "sales_channel",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Savdo kanali",
                    ),
                ),
                (
                    "sales_prefix_1c",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="1C uchun savdo raqami prefiksi",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_cashiers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Faqat shu kassirlar kira oladi. Bo'sh — hamma kira oladi.",
                        related_name="registers",
                        to="sales.cashier",
                    ),
                ),
                (
                    "register",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings_row",
                        to="sales.register",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kassa sozlamasi",
                "verbose_name_plural": "Kassa sozlamalari",
            },
        ),
    ]
