# Generated by Django 5.1.5 on 2026-09-02 09:26

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_registersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="KassaRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=32, unique=True)),
                ("file", models.FileField(upload_to=sales.models._release_path)),
                ("size", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Nima o'zgardi — kassirga ko'rinadi"
                    ),
                ),
                (
                    "mandatory",
                    models.BooleanField(default=False, verbose_name="Majburiy"),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kassa versiyasi",
                "verbose_name_plural": "Kassa versiyalari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="register",
            name="app_version",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
