# Generated by Django 5.1.5 on 2026-09-02 10:13

from django.db import migrations, models


def _blank_old_default(apps, schema_editor):
    # Eski standart «Chakana narx» — MoySklad'dagi nom emas. Bo'shatamiz:
    # bo'sh = savdo nuqtasining narx turi (to'g'ri xatti-harakat).
    RegisterSettings = apps.get_model("sales", "RegisterSettings")
    RegisterSettings.objects.filter(price_type="Chakana narx").update(price_type="")


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_kassarelease"),
    ]

    operations = [
        migrations.AddField(
            model_name="registersettings",
            name="allow_price_type_switch",
            field=models.BooleanField(
                default=True, verbose_name="Kassirga narx turini almashtirishga ruxsat"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="price_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="registersettings",
            name="price_type",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Narx turi"
            ),
        ),
        migrations.RunPython(_blank_old_default, migrations.RunPython.noop),
    ]
