# Generated by Django 5.1.5 on 2026-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_price_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="registersettings",
            name="organization_ms_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="MoySklad tashkiloti"
            ),
        ),
        migrations.AddField(
            model_name="registersettings",
            name="warehouse_ms_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="MoySklad ombori"
            ),
        ),
    ]
