# Generated by Django 5.1.5 on 2026-09-02 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_moysklad_bindings"),
        ("sales", "0007_moysklad_bindings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registers",
                to="catalog.retailstore",
            ),
        ),
    ]
