# Generated by Django 5.1.5 on 2026-09-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_register_store_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="password_plain",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
