# Generated by Django 5.1.5 on 2026-09-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_alter_registersettings_allow_price_type_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="local_uuid",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
