# Generated by Django 5.1.5 on 2026-09-08 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_moysklad_bindings"),
        ("sales", "0012_deactivate_demo_cashier"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Faol")),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "earn_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="Ball berish (%)",
                    ),
                ),
                (
                    "redeem_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Ball bilan to'lashga ruxsat"
                    ),
                ),
                (
                    "max_redeem_percent",
                    models.IntegerField(
                        default=100, verbose_name="Eng ko'p ball to'lovi (%)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bonus dasturi",
                "verbose_name_plural": "Bonus dasturi",
            },
        ),
        migrations.RemoveField(
            model_name="register",
            name="password_plain",
        ),
        migrations.CreateModel(
            name="BonusEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("earn", "Berildi"),
                            ("spend", "Sarflandi"),
                            ("return", "Qaytarish"),
                            ("import", "MoySklad'dan"),
                            ("adjust", "Qo'lda tuzatish"),
                        ],
                        max_length=8,
                    ),
                ),
                ("delta", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("comment", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_entries",
                        to="catalog.customer",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_entries",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ball harakati",
                "verbose_name_plural": "Ball harakatlari",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "-created_at"],
                        name="sales_bonus_custome_1083a7_idx",
                    )
                ],
            },
        ),
    ]
