# Generated by Django 5.1.5 on 2026-09-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0013_bonusprogram_remove_register_password_plain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
