# Generated by Django 5.1.5 on 2026-09-11 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0015_tolov_turlari_royxati"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoySkladCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("deploy", "Deploy"),
                            ("periodic", "Vaqti-vaqti bilan"),
                            ("manual", "Qo'lda"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("ok", models.BooleanField(default=False)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("leftovers", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "MoySklad sinovi",
                "verbose_name_plural": "MoySklad sinovlari",
                "ordering": ["-started_at"],
            },
        ),
    ]
