# Generated by Django 5.1.5 on 2026-09-11 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0016_moysklad_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="KassaSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=64, unique=True)),
                ("device", models.CharField(max_length=64)),
                ("device_name", models.CharField(blank=True, max_length=128)),
                ("cashier_id", models.IntegerField(default=0)),
                ("cashier_name", models.CharField(blank=True, max_length=128)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="sales.register",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kassa sessiyasi",
                "verbose_name_plural": "Kassa sessiyalari",
            },
        ),
    ]
