# Generated by Django 5.1.5 on 2026-09-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_sale_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoperation',
            name='local_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='origin_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem'),
        ),
    ]
