# Generated by Django 5.1.5 on 2026-09-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_receipt_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
    ]
