# Generated by Django 5.1.5 on 2026-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_unified_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='local_pending',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='local_queue_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='local_queue_error',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='register',
            name='local_stuck',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
