# Generated by Django 5.1.5 on 2026-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0024_stray_sales_to_their_shift"),
    ]

    operations = [
        migrations.CreateModel(
            name="PanelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avg_receipt_target",
                    models.BigIntegerField(
                        default=0,
                        help_text="Tiyinda; 0 — belgilanmagan",
                        verbose_name="O'rtacha chek maqsadi",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Panel sozlamasi",
                "verbose_name_plural": "Panel sozlamalari",
            },
        ),
    ]
