# Generated by Django 5.2.17 on 2026-09-29 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_current_prices(apps, schema_editor):
    alias = schema_editor.connection.alias
    Register = apps.get_model('sales', 'Register')
    Settings = apps.get_model('sales', 'RegisterSettings')
    Policy = apps.get_model('sales', 'RegisterPricePolicy')
    PriceType = apps.get_model('catalog', 'PriceType')
    rows = list(PriceType.objects.using(alias).order_by('sort', 'name').values('ms_id', 'name'))
    for register in Register.objects.using(alias).select_related('store').iterator():
        settings = Settings.objects.using(alias).filter(register_id=register.pk).first()
        wanted = (settings.price_type if settings else '').strip().lower()
        target = next((str(r['ms_id']) for r in rows if wanted and r['name'].strip().lower() == wanted), '')
        store_type = str(register.store.price_type_ms_id or '') if register.store_id else ''
        if not target and any(str(r['ms_id']) == store_type for r in rows):
            target = store_type
        if not target:
            target = next((str(r['ms_id']) for r in rows if any(w in r['name'].lower()
                          for w in ('чакана', 'chakana', 'розничн', 'retail'))), '')
        if not target and rows:
            target = str(rows[0]['ms_id'])
        Policy.objects.using(alias).create(register_id=register.pk, target_type=target, accepted_types=[target])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_panelsettings'),
        ('catalog', '0008_resend_pack_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPricePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('revision', models.UUIDField(default=uuid.uuid4)),
                ('accepted_types', models.JSONField(default=list)),
                ('register', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.register')),
            ],
        ),
        migrations.RunPython(seed_current_prices, migrations.RunPython.noop),
    ]
